export default function SiteFooter() {
  return (
    <footer className="mt-12 border-t border-sh-border bg-white">
      <div className="mx-auto max-w-6xl px-6 py-6 text-sm text-sh-muted">
        <p>
          © {new Date().getFullYear()} Royal Cyber · Shopify Practice Insights.
          Generated by the Shopify Department Agent &amp; Weekly Plan Agent.
        </p>
        <p className="mt-1 text-xs text-[#9CA3AF]">
          Content reflects the most recent agent run. Update the data files to refresh.
        </p>
      </div>
    </footer>
  );
}
